USE master
GO
CREATE DATABASE FIAMBRERIA
GO
USE FIAMBRERIA
GO

CREATE TABLE PROVEEDORES(
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(50) NOT NULL,
)
GO
CREATE TABLE MARCAS(
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(50) NOT NULL,
)
GO
CREATE TABLE PRODUCTOS(
ID int NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(50) NOT NULL,
IDMARCA INT NOT NULL FOREIGN KEY REFERENCES MARCAS(ID),
IDPROVEEDOR INT NOT NULL FOREIGN KEY REFERENCES PROVEEDORES(ID),
)

Select P.ID, P.NOMBRE, M.NOMBRE, PROV.NOMBRE from PRODUCTOS AS P
INNER JOIN MARCAS AS M ON M.ID = P.IDMARCA
INNER JOIN PROVEEDORES AS PROV ON PROV.ID = P.IDPROVEEDOR

Select * from PROVEEDORES