USE master
GO
CREATE DATABASE FIAMBRERIA
GO
USE FIAMBRERIA
GO

CREATE TABLE PROVEEDORES(
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(50) NOT NULL
)
GO
CREATE TABLE MARCAS(
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(50) NOT NULL
)
GO
CREATE TABLE CATEGORIAS(
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(100) NOT NULL
)
GO
CREATE TABLE PRODUCTOS(
ID int NOT NULL PRIMARY KEY IDENTITY(1,1),
IDCATEGORIA INT FOREIGN KEY REFERENCES CATEGORIAS(ID) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
IDMARCA INT NOT NULL FOREIGN KEY REFERENCES MARCAS(ID),
PRECIOUNITARIO MONEY NOT NULL,
STOCK INT NOT NULL DEFAULT(0),
IDPROVEEDOR INT NOT NULL FOREIGN KEY REFERENCES PROVEEDORES(ID)
)

Select P.ID, P.NOMBRE, M.NOMBRE,P.PRECIOUNITARIO ,P.STOCK, PROV.NOMBRE,C.NOMBRE from PRODUCTOS AS P
INNER JOIN MARCAS AS M ON M.ID = P.IDMARCA
INNER JOIN PROVEEDORES AS PROV ON PROV.ID = P.IDPROVEEDOR
INNER JOIN CATEGORIAS AS C ON C.ID = P.IDCATEGORIA
Where C.NOMBRE like 'Fiambres'

Select * from PROVEEDORES
